# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a7aedfda29950b06ff1b2768aa75e1fbd792abf80447a75823797662c5c299a31adf7d397fea62029f3ec3b60b39b2c6a117f9c589ab874edd6015afcbc4c13b

test:
  secret_key_base: c2c7a9af31ff5b47f4c3ab134780e86dbf30309617cd7e79141835447aca7a92dacb0d6a4669d05bcc31ae1493e9eb031b75c13b0abff37b8b42c41e72ec45f6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
